"""Writes src/math_tables.hpp, the constants and tables behind crowdbook::math.

    python3 tools/math_tables.py > src/math_tables.hpp

Every value is worked out to 60 significant digits with the standard library's decimal module and
then rounded to the nearest double, so the tables do not depend on any platform's libm.
"""

from decimal import Decimal, getcontext

getcontext().prec = 60

LN2 = Decimal(2).ln()
EXP_STEPS = 64  # exp splits off multiples of ln 2 / 64
LOG_STEPS = 128  # log divides by the nearest of 1 + i / 128
LOG_FIRST, LOG_LAST = -38, 54  # covers mantissas from 1/sqrt(2) to sqrt(2)


def nearest(value: Decimal) -> float:
    return float(value)  # float() of a Decimal is correctly rounded


def split(value: Decimal) -> tuple[float, float]:
    """The nearest double, and the nearest double to what it leaves out."""
    hi = nearest(value)
    return hi, nearest(value - Decimal(hi))


def truncated(value: Decimal, bits: int) -> tuple[float, float]:
    """`value` to `bits` binary places, which a small whole number multiplies exactly, and the
    nearest double to the rest."""
    scale = Decimal(2) ** bits
    hi = float((value * scale).to_integral_value()) / float(scale)
    return hi, nearest(value - Decimal(hi))


def literal(x: float) -> str:
    return x.hex() if x != 0.0 else "0x0p+0"


def main() -> None:
    ln2_hi, ln2_lo = truncated(LN2, 41)  # times an exponent of at most 1,100 stays exact
    step = LN2 / EXP_STEPS
    step_hi, step_lo = truncated(step, 42)  # times a multiple of at most 2^17 stays exact
    ln2_nearest, ln2_rest = split(LN2)
    lines = [
        "// Generated by tools/math_tables.py; do not edit.",
        "#pragma once",
        "",
        "#include <array>",
        "",
        "namespace crowdbook::math::detail {",
        "",
        "// ln 2 in two parts; an exponent times the first, of 41 bits, is exact.",
        f"inline constexpr double kLn2Hi = {literal(ln2_hi)};",
        f"inline constexpr double kLn2Lo = {literal(ln2_lo)};",
        "// ln 2 to the nearest double, and the rest.",
        f"inline constexpr double kLn2 = {literal(ln2_nearest)};",
        f"inline constexpr double kLn2Rest = {literal(ln2_rest)};",
        f"// ln 2 / {EXP_STEPS} in two parts, the first short enough that k times it is exact, and",
        f"// {EXP_STEPS} / ln 2 to pick k.",
        f"inline constexpr double kStepHi = {literal(step_hi)};",
        f"inline constexpr double kStepLo = {literal(step_lo)};",
        f"inline constexpr double kStepsPerLn2 = {literal(nearest(EXP_STEPS / LN2))};",
        "",
        f"// 2^(j / {EXP_STEPS}) for j from 0 to {EXP_STEPS - 1}, each as the nearest double"
        " and the rest.",
        f"inline constexpr std::array<std::array<double, 2>, {EXP_STEPS}> kExp2Steps{{{{",
    ]
    for j in range(EXP_STEPS):
        hi, lo = split((LN2 * j / EXP_STEPS).exp())
        lines.append(f"    {{{literal(hi)}, {literal(lo)}}},")
    lines += [
        "}};",
        "",
        f"// For i from {LOG_FIRST} to {LOG_LAST}: the nearest double to 1 / (1 + i / {LOG_STEPS}),"
        " and minus the",
        "// logarithm of that double, as the nearest double and the rest.",
        f"inline constexpr int kLogFirst = {LOG_FIRST};",
        f"inline constexpr std::array<std::array<double, 3>, {LOG_LAST - LOG_FIRST + 1}>"
        " kLogSteps{{",
    ]
    for i in range(LOG_FIRST, LOG_LAST + 1):
        inverse = nearest(1 / (1 + Decimal(i) / LOG_STEPS))
        hi, lo = split(-Decimal(inverse).ln())
        lines.append(f"    {{{literal(inverse)}, {literal(hi)}, {literal(lo)}}},")
    lines += ["}};", "", "} // namespace crowdbook::math::detail"]
    print("\n".join(lines))


if __name__ == "__main__":
    main()
